name: 'Publish release candidate'
on:
  push:
    branches:
      - pipeline
jobs:
  check-build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build

  publish:
    needs: [check-build]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: git config user.name 'github-actions'; git config user.email 'github-actions@github.com';
      - run: npm run build
      - run: npm run release:rc
